### ISSUE TITLE
Add Click sound

### ISSUE THREAD

**Issue by BarmenduC** [DecodersCommunity/calculator#13]
Add a sound effect to the user action of clicking a button on the calculator.

**Comment by dhruvdabhi101** [comment]
i would like to contribute.

**Comment by harsitagarwalla187** [comment]
Can i work in this issue?

**Comment by BarmenduC** [comment]
Hey @dhruvdabhi101 @harsitagarwalla187 @Revathi-80 

I have assigned this issue to all three of you. The first to make a suitable PR will be merged.
